"use strict";

import {
	REQUEST_LOAD_GROUPS,
	RECEIVE_LOAD_GROUPS,
	REQUEST_LOAD_GROUP_CUSTS,
	RECEIVE_LOAD_GROUP_CUSTS,
	REQUEST_LOAD_CUSTS,
	RECEIVE_LOAD_CUSTS,
	REQUEST_ADD_CUSTS_TO_GROUP,
	RECEIVE_ADD_CUSTS_TO_GROUP,
	REQUEST_DELETE_CUSTS_TO_GROUP,
	RECEIVE_DELETE_CUSTS_TO_GROUP,
	START_LOADING,
	STOP_LOADING,
} from "../actions";

export const isLoading = (state=false, action) => {
	switch(action.type){
	case REQUEST_LOAD_GROUPS:
	case RECEIVE_LOAD_GROUPS:
	case REQUEST_LOAD_GROUP_CUSTS:
	case RECEIVE_LOAD_GROUP_CUSTS:
	case REQUEST_LOAD_CUSTS:
	case RECEIVE_LOAD_CUSTS:
	case REQUEST_ADD_CUSTS_TO_GROUP:
	case RECEIVE_ADD_CUSTS_TO_GROUP:
	case REQUEST_DELETE_CUSTS_TO_GROUP:
	case RECEIVE_DELETE_CUSTS_TO_GROUP:
	case START_LOADING:
	case STOP_LOADING:
		return action.isLoading;
	default:
		return state;
	}
};
    