"use strict";

import {
	REQUEST_LOAD_GROUPS,
	RECEIVE_LOAD_GROUPS,
	REQUEST_LOAD_ALL_PERMISSIONS,
	RECEIVE_LOAD_ALL_PERMISSIONS,
	REQUEST_LOAD_GROUP_PERMISSIONS,
	RECEIVE_LOAD_GROUP_PERMISSIONS,
	REQUEST_ADD_PERMISSION,
	RECEIVE_ADD_PERMISSION,
	REQUEST_REMOVE_PERMISSION,
	RECEIVE_REMOVE_PERMISSION,
	START_LOADING,
	STOP_LOADING,
} from "../actions";

export const isLoading = (state=false, action) => {
	switch(action.type){
	case REQUEST_LOAD_GROUPS:
	case RECEIVE_LOAD_GROUPS:
	case REQUEST_LOAD_ALL_PERMISSIONS:
	case RECEIVE_LOAD_ALL_PERMISSIONS:
	case REQUEST_LOAD_GROUP_PERMISSIONS:
	case RECEIVE_LOAD_GROUP_PERMISSIONS:
	case REQUEST_ADD_PERMISSION:
	case RECEIVE_ADD_PERMISSION:
	case REQUEST_REMOVE_PERMISSION:
	case RECEIVE_REMOVE_PERMISSION:
	case START_LOADING:
	case STOP_LOADING:
		return action.isLoading;
	default:
		return state;
	}
};
